### PR TITLE
pkg/client/stream: fix deadlock for client methods

### LINKED ISSUE #273: Environment.QueryOffset hang/deadlock
### Describe the bug

Hello!
I met the scenario when call to the Environment.QueryOffset may hang: 

```go
package main

import (
	"fmt"
	"os"

	"github.com/rabbitmq/rabbitmq-stream-go-client/pkg/stream"
)

func CheckErr(err error) {
	if err != nil {
		fmt.Printf("%s ", err)
		os.Exit(1)
	}
}

func main() {
	env, err := stream.NewEnvironment(
		stream.NewEnvironmentOptions().
			SetHost("localhost").
			SetPort(5552).
			SetUser("guest").
			SetPassword("guest"))
	CheckErr(err)

	off, err := env.QueryOffset("consumer", "stream")
	fmt.Println(off, err)
}

```

Here is a description:
[`Environment.QueryOffset` calls](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/environment.go#L183) `Client.queryOffset` which internally:

1. [calls](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L721)     [`Client.handleWriteWithResponse`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/socket.go#L68-L83) with `removeResponse` argument passed as false (so RemoveResponseById won't be called and closing of response.data channel wouldn't be performed). The last function [calls `waitCodeWithDefaultTimeOut`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/utils.go#L33-L50)
2. right after returning from the `handleWriteWithResponse` `queryOffset` starts accepting the offset value on the channel [here is a code on the next line](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L722).

Thus there may occur a deadlock, when the response was finished by timeout (for example rabbit service unavailable), but the `Client.queryOffset` method still waiting the data on channel which wouldn't be closed. Seems that error check should be added before reading from channel, like it's done at [`Client.open`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L318-L327).
I suppose that next methods also may have a deadlock: [`Client.StreamStats`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L848-L853) and [`Client.queryPublisherSequence`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L607-L612)

### Reproduction steps

1. start rabbitmq server
2. setup breakpoint on this [line](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L721)
3. run the code from the description and wait on the breakpoint
4. stop the rabbitmq server
5. continue code execution

### Expected behavior

No hang

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HustonMmmavr**
Client.queryOffset/queryPublisherSequence/StreamStats were fixed to prevent deadlock in case of request timeout (for example rabbit server is down). Now these methods returns error immidiately if it occured and doesn't try to read from data chanel, because in case of request timeout it hangs (no other gorouitine would write to this channel).

Also Client is extended with additional field socketCallTimeout, for testing purposes (decrease running time of new tests).

Closes #273

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@HustonMmmavr Thank you for the PR
At the moment we are busy with other tasks. We will have a look as soon as possible. 
Please have a bit of patience :)

File: pkg/stream/coordinator.go [hunk 1]
```diff
@@ -132,7 +132,7 @@ func newResponse(commandDescription string) *Response {
 	res := &Response{}
 	res.commandDescription = commandDescription
 	res.code = make(chan Code, 1)
-	res.data = make(chan interface{})
+	res.data = make(chan interface{}, 1)
```
Comment (Gsantomaggio) [inline pkg/stream/coordinator.go:135]: Why here is it necessary to add `1` to the channel?

Comment (HustonMmmavr) [reply pkg/stream/coordinator.go:135]: It was done because the [test failed](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/f323ce5e87c4ad4b3321ef323f98130e29400318/pkg/stream/consumer_test.go#L325-L333). I found that if there is no offset for this consumer on the server the `OffsetNotFoundError` would be raised from `queryOffset` ([the error code - `responseCodeNoOffset` is send from queryOffsetFrameHandler](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/f323ce5e87c4ad4b3321ef323f98130e29400318/pkg/stream/server_frame.go#L431)), but a bit later the [0 offset would be send to the non buffered `data` chanel](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/f323ce5e87c4ad4b3321ef323f98130e29400318/pkg/stream/server_frame.go#L431) thus the `queryOffsetFrameHandler` hangs until `queryOffset` would read from channel (but this function already exited - there is no readers) as a result `Client.handleResponse` loop hangs too. So I've made data channel buffered, like it's done for the code channel.

**Comment by Gsantomaggio** [comment]
@HustonMmmavr I am testing the PR and it seems to be ok. May I ask to resolve the conflicts so I will merge!
Thank you

**Comment by Gsantomaggio** [comment]
Thank you

**Comment by HustonMmmavr** [comment]
Thanks)
